spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./h2testdb
    username: h2
    password:

  h2:
    console:
      enabled: false
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8081





